from flask_wtf import Form
from wtforms.fields.html5 import DateTimeField, DateField
from wtforms import SubmitField, TextField, SelectMultipleField
from wtforms.validators import Required

country_list = [
        ("010011010110111101100100", "010011010110111101100100"),
        ("Albania", "Albania"),
        ("Argentina", "Argentina"),
        ("Armenia", "Armenia"),
        ("Australia", "Australia"),
        ("Austria", "Austria"),
        ("Azerbaijan", "Azerbaijan"),
        ("Belarus", "Belarus"),
        ("Belgium", "Belgium"),
        ("Bolivia", "Bolivia"),
        ("Bosnia and Herzegovina", "Bosnia and Herzegovina"),
        ("Brazil", "Brazil"),
        ("Brazil (Indian Day)", "Brazil (Indian Day)"),
        ("Bulgaria", "Bulgaria"),
        ("Canada", "Canada"),
        ("Catalonia", "Catalonia"),
        ("Chile", "Chile"),
        ("China", "China"),
        ("Colombia", "Colombia"),
        ("Congo, The Democratic Republic of the", "Congo, The Democratic Republic of the"),
        ("Croatia", "Croatia"),
        ("Czech Republic", "Czech Republic"),
        ("Denmark", "Denmark"),
        ("Ecuador", "Ecuador"),
        ("Egypt", "Egypt"),
        ("England (St. George's Day)", "England (St. George's Day)"),
        ("Estonia", "Estonia"),
        ("Finland", "Finland"),
        ("France", "France"),
        ("Free State of Bavaria", "Free State of Bavaria"),
        ("Germany", "Germany"),
        ("Greece", "Greece"),
        ("Guam", "Guam"),
        ("Hong Kong", "Hong Kong"),
        ("Hungary", "Hungary"),
        ("Hyper-Israel", "Hyper-Israel"),
        ("Iceland", "Iceland"),
        ("India", "India"),
        ("Indonesia", "Indonesia"),
        ("Ireland", "Ireland"),
        ("Italy", "Italy"),
        ("Japan", "Japan"),
        ("Kazakhstan", "Kazakhstan"),
        ("Korea, Republic of", "Korea, Republic of"),
        ("Kyrgyzstan", "Kyrgyzstan"),
        ("Latvia", "Latvia"),
        ("Lebanon", "Lebanon"),
        ("Lithuania", "Lithuania"),
        ("Luxembourg", "Luxembourg"),
        ("Mexico", "Mexico"),
        ("Moldova, Republic of", "Moldova, Republic of"),
        ("Monaco", "Monaco"),
        ("Montenegro", "Montenegro"),
        ("Morocco", "Morocco"),
        ("Netherlands", "Netherlands"),
        ("New Zealand", "New Zealand"),
        ("Nicaragua", "Nicaragua"),
        ("Norway", "Norway"),
        ("Palestinian Territory, Occupied", "Palestinian Territory, Occupied"),
        ("Paraguay", "Paraguay"),
        ("Peru", "Peru"),
        ("Philippines", "Philippines"),
        ("Poland", "Poland"),
        ("Portugal", "Portugal"),
        ("Puerto Rico", "Puerto Rico"),
        ("Quebec", "Quebec"),
        ("Republic of Texas", "Republic of Texas"),
        ("Reunion", "Reunion"),
        ("Romania", "Romania"),
        ("Russian Federation", "Russian Federation"),
        ("Saudi Arabia", "Saudi Arabia"),
        ("Scotland", "Scotland"),
        ("Serbia", "Serbia"),
        ("Slovakia", "Slovakia"),
        ("Slovenia", "Slovenia"),
        ("Spain", "Spain"),
        ("Spain (Anniversary of the Second Spanish Republic)", "Spain (Anniversary of the Second Spanish Republic)"),
        ("Sri Lanka", "Sri Lanka"),
        ("Sweden", "Sweden"),
        ("Switzerland", "Switzerland"),
        ("Taiwan, Province of China", "Taiwan, Province of China"),
        ("Thailand", "Thailand"),
        ("The Illuminati", "The Illuminati"),
        ("Tringapore", "Tringapore"),
        ("Turkey", "Turkey"),
        ("Ukraine", "Ukraine"),
        ("United Kingdom", "United Kingdom"),
        ("United States", "United States"),
        ("Uruguay", "Uruguay"),
        ("Uzbekistan", "Uzbekistan"),
        ("Venezuela", "Venezuela")
        ]

class QueryForm(Form):
    datefrom = DateField('Start date')
    dateto = DateField('End date')
    text = TextField('Post content search')

    country = SelectMultipleField(label="Countries (use CTRL for multiple select)", choices=country_list)
    submit = SubmitField("Submit")
